#!/usr/bin/env pwsh
# Windows / PowerShell equivalent of bootstrap-local.sh.

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

if (-not (Get-Command azd -ErrorAction SilentlyContinue)) {
    Write-Error "azd CLI not found. Install: https://aka.ms/azd"
    exit 1
}

if (-not ((azd env list 2>$null) -match '\*')) {
    Write-Error "No active azd environment. Run: azd env new dev && azd up"
    exit 1
}

Write-Host "→ Generating backend/.env from azd env"
$EnvFile = "backend/.env"
if (Test-Path $EnvFile) {
    Copy-Item $EnvFile "$EnvFile.bak"
    Write-Host "   (existing .env backed up to $EnvFile.bak)"
}

$values = @{}
azd env get-values | ForEach-Object {
    if ($_ -match '^([^=]+)="?(.*?)"?$') {
        $values[$matches[1]] = $matches[2]
    }
}

$mapping = @{
    "BACKEND_API_KEY"                  = "BACKEND_API_KEY"
    "AZURE_OPENAI_ENDPOINT"            = "AZURE_OPENAI_ENDPOINT"
    "AZURE_OPENAI_ANALYSIS_DEPLOYMENT" = "AZURE_OPENAI_ANALYSIS_DEPLOYMENT"
    "AZURE_OPENAI_IMAGE_DEPLOYMENT"    = "AZURE_OPENAI_IMAGE_DEPLOYMENT"
    "STORAGE_ACCOUNT_NAME"             = "AZURE_STORAGE_ACCOUNT_NAME"
    "BLOB_CONTAINER_NAME"              = "BLOB_CONTAINER_NAME"
    "COSMOS_ENDPOINT"                  = "COSMOS_ENDPOINT"
    "COSMOS_DATABASE_NAME"             = "COSMOS_DATABASE_NAME"
    "COSMOS_CONTAINER_NAME"            = "COSMOS_CONTAINER_NAME"
}

$lines = @(
    "# Generated by scripts/bootstrap-local.ps1 — do not commit.",
    "# Re-run the script after ``azd up`` to refresh.",
    ""
)
foreach ($key in $mapping.Keys) {
    if ($values.ContainsKey($key)) {
        $lines += "$($mapping[$key])=$($values[$key])"
    }
}
$lines += ""
$lines += "AZURE_OPENAI_API_VERSION=2025-04-01-preview"
$lines += "LOG_LEVEL=INFO"
$lines += "CORS_ORIGINS=http://localhost:5173"

Set-Content -Path $EnvFile -Value $lines
Write-Host "   ✅ $EnvFile written"

Write-Host "→ Backend venv + deps"
if (-not (Test-Path backend/.venv)) {
    python -m venv backend/.venv
}
& backend/.venv/Scripts/python.exe -m pip install --quiet --upgrade pip
& backend/.venv/Scripts/python.exe -m pip install --quiet -e "backend[dev]"
Write-Host "   ✅ backend/.venv ready"

Write-Host "→ Frontend deps"
Push-Location frontend
npm install --silent
Pop-Location
Write-Host "   ✅ frontend/node_modules ready"

Write-Host @"

🎉 Local bootstrap complete.

Next:
  make dev      # backend (uvicorn) + frontend (vite) in parallel
  make test     # pytest + tsc
  make rbac     # grant your user the 3 data-plane roles needed for local dev

"@
