#!/usr/bin/env bash
# Bootstrap local development for create-ad-cut.
#
# Idempotent — safe to re-run.
#   1. Reads `azd env get-values` and writes backend/.env (backs up prior).
#   2. Creates backend/.venv + installs dev deps.
#   3. Installs frontend npm deps.
#
# Prerequisites: azd auth login + az login + `azd env new <name>` + `azd up`
# have already run at least once for this repo.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v azd >/dev/null 2>&1; then
  echo "❌ azd CLI not found. Install: https://aka.ms/azd" >&2
  exit 1
fi

if ! azd env list 2>/dev/null | grep -q '\*'; then
  echo "❌ No active azd environment. Run: azd env new dev && azd up" >&2
  exit 1
fi

echo "→ Generating backend/.env from azd env"
ENV_FILE="backend/.env"
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "   (existing .env backed up to ${ENV_FILE}.bak)"
fi

# Map azd outputs → backend env. Only the keys backend/app/config.py expects.
{
  echo "# Generated by scripts/bootstrap-local.sh — do not commit."
  echo "# Re-run the script after \`azd up\` to refresh."
  echo ""

  # azd env get-values prints `KEY="value"` per line. Pipe through a tiny
  # awk filter to drop quotes and keep only the names we care about.
  azd env get-values | awk -F'=' '
    /^BACKEND_API_KEY=/        { print "BACKEND_API_KEY=" substr($0, index($0,"=")+1); next }
    /^AZURE_OPENAI_ENDPOINT=/  { print "AZURE_OPENAI_ENDPOINT=" substr($0, index($0,"=")+1); next }
    /^AZURE_OPENAI_ANALYSIS_DEPLOYMENT=/ { print "AZURE_OPENAI_ANALYSIS_DEPLOYMENT=" substr($0, index($0,"=")+1); next }
    /^AZURE_OPENAI_IMAGE_DEPLOYMENT=/    { print "AZURE_OPENAI_IMAGE_DEPLOYMENT=" substr($0, index($0,"=")+1); next }
    /^STORAGE_ACCOUNT_NAME=/   { print "AZURE_STORAGE_ACCOUNT_NAME=" substr($0, index($0,"=")+1); next }
    /^BLOB_CONTAINER_NAME=/    { print "BLOB_CONTAINER_NAME=" substr($0, index($0,"=")+1); next }
    /^COSMOS_ENDPOINT=/        { print "COSMOS_ENDPOINT=" substr($0, index($0,"=")+1); next }
    /^COSMOS_DATABASE_NAME=/   { print "COSMOS_DATABASE_NAME=" substr($0, index($0,"=")+1); next }
    /^COSMOS_CONTAINER_NAME=/  { print "COSMOS_CONTAINER_NAME=" substr($0, index($0,"=")+1); next }
  ' | sed 's/"//g'

  echo ""
  echo "AZURE_OPENAI_API_VERSION=2025-04-01-preview"
  echo "LOG_LEVEL=INFO"
  echo "CORS_ORIGINS=http://localhost:5173"
} > "$ENV_FILE"

echo "   ✅ $ENV_FILE written"

echo "→ Backend venv + deps"
if [ ! -d backend/.venv ]; then
  python3 -m venv backend/.venv
fi
# shellcheck disable=SC1091
source backend/.venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -e "backend[dev]"
deactivate
echo "   ✅ backend/.venv ready"

echo "→ Frontend deps"
( cd frontend && npm install --silent )
echo "   ✅ frontend/node_modules ready"

cat <<EOF

🎉 Local bootstrap complete.

Next:
  make dev      # backend (uvicorn) + frontend (vite) in parallel
  make test     # pytest + tsc
  make rbac     # grant your user the 3 data-plane roles needed for local dev

EOF
